DEFAULTS: &DEFAULTS

development:
  <<: *DEFAULTS
  secret_key_base: 2d3fce23189eca2d77283565301fe8ff6d7a61fa4d3d99060b8af0a9f16c2

test:
  <<: *DEFAULTS
  secret_key_base: 97f44883351b550f74069ee0700187e7ae7b788d3f795d6bd3d82cc524548

production:
  secret_key_base: <%= ENV['READER_SECRET_KEY_BASE'] %>
